---
kind: "operation"
client: "rug-cli 0.16.3"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "24b88f7*"
  parameters:
    - "repo_slug": "atomisthqa/handlers"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.29.0-SNAPSHOT"
editor:
  name: "AddTypeScriptEventHandler"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.23.0"
  origin:
    repo: "https://357fa2ba6de62595b938013dac8be8ad996a84a9@github.com/atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "1bc7539"
  parameters:
    - "handlerName": "Tag"
    - "description": "Simple handler to catch any Tag event"
    - "pathExpression": "/Tag()"

---
kind: "operation"
client: "rug-cli 0.29.0-SNAPSHOT"
editor:
  name: "AddTypeScriptCommandHandler"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.23.0"
  origin:
    repo: "https://357fa2ba6de62595b938013dac8be8ad996a84a9@github.com/atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "1bc7539"
  parameters:
    - "handlerName": "Tag"
    - "description": "Simple command to tag a sha in GitHub"
    - "intent": "create tag"

