---
kind: "operation"
client: "rug-cli 0.16.3"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "update-maven"
    sha: "24b88f7*"
  parameters:
    - "repo_slug": "atomisthqa/handlers"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "atomist"
editor:
  name: "atomist-rugs.python-library.AddPythonGitignore"
  group: "atomist-rugs"
  artifact: "python-library"
  version: "0.1.3"
  origin:
    repo: "atomist-rugs/python-library.git"
    branch: "27e2621967c3b8bb1330e802c90c467b7f693f4a"
    sha: "27e2621"

